 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2022-12-22 02:07:37,777] ERROR in app: Exception on /todo1 [GET]
Traceback (most recent call last):
  File "/Users/yuyungwang/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yuyungwang/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yuyungwang/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/yuyungwang/opt/anaconda3/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/yuyungwang/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "api.py", line 13, in get
    return {todo_id: todos[todo_id]}
KeyError: 'todo1'
127.0.0.1 - - [22/Dec/2022 02:07:37] "[35m[1mGET /todo1 HTTP/1.1[0m" 500 -
127.0.0.1 - - [22/Dec/2022 02:07:42] "[37mPUT /todo1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [22/Dec/2022 02:07:43] "[37mGET /todo1 HTTP/1.1[0m" 200 -
